input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "Admin@123"
    index => "k8s-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
